version: "3.9"

services:
  # api:
  #   build: ./sample-api
  #   image: api
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - NODE_ENV=production
  #   # Run the command from the build context
  #   command: npm start


  # api:
  #   build:
  #     context: ./sample-api
  #     dockerfile: Dockerfile
  #   image: api
  #   ports:
  #     - 3001:3001
  #   # Run the command from the build context
  #   command: npm start

  client:
    build: ./sample-client
    image: client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      # - API_HOST=http://api:1080
      - API_HOST=http://localhost:3001
    # Run the command from the build context
    command: npm run dev

  # test:
  #   build:
  #     context: .
  #   image: test
  #   volumes:
  #     - .:/app
  #   environment:
  #     # - BASE_URL=http://client:3000
  #     - API_HOST=http://localhost:3000
  
