version: "3.9"

services:
  api:
    build: ./test-api
    profiles:
      - test

  client:
    build: ./test-client
    profiles:
      - test
    environment:
      - API_HOST=http://api:3001

  mongo:
    image: mongo:4.0.27
    volumes:
      - ./test-api/database/animal-facts.json:/database/animal-facts.json
      - ./test-api/database/seed.sh:/docker-entrypoint-initdb.d/seed.sh
    environment:
      - MONGO_INITDB_DATABASE=animal-facts
    ports:
      - 27017:27017

  test:
    build: .
    profiles:
      - test
    environment:
      - BASE_URL=http://client:3000

# For local development

  local-client:
    build: ./test-client
    ports:
      - 3000:3000
    environment:
      - API_HOST=http://localhost:3001
    profiles:
      - local

  local-api:
    build: ./test-api
    ports:
      - 3001:3001
    profiles:
      - local
