version: "3.9"

services:
  api:
    build: ./test-api
    image: api
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001
    # Run the command from the build context
    command: npm start

  client:
    build:
      context: ./test-client
      dockerfile: Dockerfile
    image: client
    environment:
      - NODE_ENV=production
      - API_HOST=http://localhost:3001
    # volumes:
    #   - .:/app
    ports:
      - 3000:3000
    # Run the command from the build context
    command: npm run dev
