version: "3.9"

services:
  api:
    build: ./test-api
    image: api
    environment:
      - NODE_ENV=production
    # Run the command from the build context
    command: npm start

  client:
    build:
      context: ./test-client
      dockerfile: Dockerfile
    image: client
    environment:
      - NODE_ENV=production
      - API_HOST=http://api:3001
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://client:3000"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    command: npm run dev

  test:
    build:
      context: .
    image: test
    volumes:
      - .:/app
    environment:
      - BASE_URL=http://client:3000
  #   # depends_on:
  #   #   client:
  #   #     condition: service_healthy
