version: "3.9"

services:
  api:
    build: ./test-api
    profiles:
      - test

  client:
    build: ./test-client
    profiles:
      - test
    environment:
      - API_HOST=http://api:3001

  test:
    build: .
    profiles:
      - test
    environment:
      - BASE_URL=http://client:3000

# For local development

  local-client:
    build: ./test-client
    ports:
      - 3000:3000
    environment:
      - API_HOST=http://localhost:3001
    profiles:
      - local

  local-api:
    build: ./test-api
    ports:
      - 3001:3001
    profiles:
      - local
